-- AlterTable
ALTER TABLE "Balance" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "OnRampTransaction" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "p2pTransfer" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;
