name: Build and Deploy to Docker Hub

on:
  push:
  # anytime ther is a push to the default branch performs the below operations.
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        # since our docker file need not be in root folder no need write this file: ./Dockerfile instead
        file: ./docker/Dockerfile.userapp
        push: true
        tags: hemanthrgowda18/tapngo:latest  # Replace with your Docker Hub username and repository

    - name: Verify Pushed Image
      run: docker pull hemanthrgowda18/tapngo:latest  # Replace with your Docker Hub username and repository
